DROP TABLE IF EXISTS player;
CREATE TABLE player
(
  id INT NOT NULL AUTO_INCREMENT,
  sid VARCHAR(32) NOT NULL,

  nick VARCHAR(16) NOT NULL,
  lv INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB DEFAULT CHARACTER SET UTF8;